const appDiv = document.getElementById('app');

const model = {
    app: {
        pages: ['loginPage', 'feedPage', 'profilePage', 'friendPage','clubPage', 'chatRoom'],
        currentPage: 'profilePage',
        isOpen: true,

        selectedUsers: {
            loggedInUser: 0,
            friendUser: 3,
            selectedClub:4,
        }
    },//app
    input: {

        login: {
            username: '',
            password: '',
        },

        registerUser: {
            id: '',
            isAdmin: false,
            email: '',
            username: '',
            password: '',
            passwordConfirm: '',
            userImages: [],
            name: '',
            age: null,
            gender: '',
            bio: '',
            occupation: '',
            interests: [],
            favoriteTeam: [],
            friendList: [],

        },

        profilePage: {
            inputFriend: '',
        },

        clubPage: {

        },
        tempMessages: {
            messagePrompt: '',
            chatTemp: '',
            loginMessage: '',
        },

        search: {
        searchInput: '',
        searchResult: '',
        searchTeamsInput: '',
        searchTeamsResult: '',
        isTeam: false,
        isNation: false,
        isCity: false,
        isManager: false,
        isLeague: false,
        },
    },//input
    data: {
        users: [
            {
                id: 0,
                isAdmin: true,
                email: 'nico@outlook.no',
                username: 'Nico',
                password: '123',
                userImages: ["Photos/Screenshot 2024-11-01 13.05.41.png", "Photos/Screenshot 2024-11-01 13.06.24.png", "Photos/Screenshot 2024-11-01 13.06.55.png"],
                name: 'Nicolai',
                age: 31,
                bio: 'Hei, jeg heter Nico',
                gender: 'Male',
                occupation: 'Student',
                interests: ['Fotball', 'Teknologi',],
                favoriteTeam: [],
                friendList: ['Roger','Anna1',],
            },

            {
                id: 1,
                isAdmin: false,
                email: 'rotta@mail.no',
                username: 'Rotta',
                password: '123',
                userImages: ["Photos/Rotta/Screenshot 2024-11-02 09.44.24.png","Photos/Rotta/Screenshot 2024-11-02 09.46.17.png","Photos/Rotta/Screenshot 2024-11-02 09.46.01.png","Photos/Rotta/Screenshot 2024-11-02 09.45.21.png","Photos/Rotta/Screenshot 2024-11-02 09.44.56.png",],
                name: 'Svein Rotta',
                age: 27,
                bio: 'Hei, jeg heter Svein Rotta',
                gender: 'Male',
                occupation: 'Rotte på heltid',
                interests: ['Dumpster diving', 'spille på slurva',],
                favoriteTeam: [],
                friendList: ['Roger',],
            },
            {
                id: 2,
                isAdmin: false,
                email: 'roger@mail.no',
                username: 'Roger',
                password: '123',
                userImages: ["Photos/Roger/Screenshot 2024-11-02 09.42.52.png","Photos/Roger/Screenshot 2024-11-02 09.43.04.png","Photos/Roger/Screenshot 2024-11-02 09.43.18.png",],
                name: 'Roger',
                age: 27,
                bio: 'Hei, jeg heter Roger',
                gender: 'Male',
                occupation: 'Skureklut på heltid',
                interests: ['Øl', 'spille på slurva', 'Pizza'],
                favoriteTeam: [],
                friendList: ['Nico', 'Rotta',],
            },

            {
                id: 3,
                isAdmin: false,
                email: 'Anna@mail.no',
                username: 'Anna1',
                password: '123',
                userImages: ["Photos/Anna/Anna1.png","Photos/Anna/anna2.png","Photos/Anna/anna3.png",],
                name: 'Anna',
                age: 27,
                bio: 'Hei, jeg heter Anna',
                gender: 'Female',
                occupation: 'Forfatter',
                interests: ['Pocketbøker', 'Stå på hodet',],
                favoriteTeam: [],
                friendList: ['Nico'],
            },
            
        ],//Users
        chatroom: [],
        footballTeams: [

            {
                clubId: 0,
                img: "IMG/Real_Madrid_CF.svg.webp",
                teamName: 'Real Madrid CF',
                leagueTitles: 35,
                cupTitles: 29,
                championsLeagueTitles: 14,
                europaLeagueTitles: 2,
                founded: 1902,
                league: 'La Liga',
                nation: 'Spain',
                city: 'Madrid',
                stadium: 'Santiago Bernabéu',
                stadiumCapacity: 81044,
                manager: 'Carlo Ancelotti',
                topScorer: 'Cristiano Ronaldo',
                topScorerGoals: 450,
                rivalClub: 'FC Barcelona',
                clubMotto: 'Hala Madrid',
                marketValue: '$5.1 billion',
                socialMediaFollowers: '450 million',
                colors: 'White',
                nicknames: ['Los Blancos'],
                annualRevenue: '$800 million',
                ownership: 'Florentino Pérez',
                notablePlayers: ['Cristiano Ronaldo', 'Raúl', 'Zinedine Zidane'],
                youthAcademy: 'La Fábrica',
                totalTrophies: 97,
                website: 'https://www.realmadrid.com',
                bio: 'Real Madrid is one of the most successful clubs in the world, known for its numerous UEFA Champions League titles and a legacy of legendary players.',
                members: '90,000+'
            },
            {
                clubId: 1,
                img: "IMG/FC_Barcelona_(crest).svg.webp",
                teamName: 'FC Barcelona',
                leagueTitles: 27,
                cupTitles: 31,
                championsLeagueTitles: 5,
                europaLeagueTitles: 0,
                founded: 1899,
                league: 'La Liga',
                nation: 'Spain',
                city: 'Barcelona',
                stadium: 'Camp Nou',
                stadiumCapacity: 99354,
                manager: 'Hans Flick',
                topScorer: 'Lionel Messi',
                topScorerGoals: 672,
                rivalClub: 'Real Madrid CF',
                clubMotto: 'Més que un club',
                marketValue: '$5 billion',
                socialMediaFollowers: '400 million',
                colors: 'Blue and Red',
                nicknames: ['Blaugrana', 'Barça'],
                annualRevenue: '$800 million',
                ownership: 'Socios (Member-owned)',
                notablePlayers: ['Lionel Messi', 'Xavi', 'Andrés Iniesta'],
                youthAcademy: 'La Masia',
                totalTrophies: 94,
                website: 'https://www.fcbarcelona.com',
                bio: 'FC Barcelona is a globally recognized club, famous for its "La Masia" academy and the philosophy of playing attractive, possession-based football.',
                members: '143,000+'
            },
            {
                clubId: 2,
                img: "IMG/Manchester_United_FC_crest.svg.webp",
                teamName: 'Manchester United FC',
                leagueTitles: 20,
                cupTitles: 12,
                championsLeagueTitles: 3,
                europaLeagueTitles: 1,
                founded: 1878,
                league: 'Premier League',
                nation: 'England',
                city: 'Manchester',
                stadium: 'Old Trafford',
                stadiumCapacity: 74879,
                manager: 'Ruben Amorim',
                topScorer: 'Wayne Rooney',
                topScorerGoals: 253,
                rivalClub: 'Liverpool FC',
                clubMotto: 'Glory Glory Man United',
                marketValue: '$4.6 billion',
                socialMediaFollowers: '350 million',
                colors: 'Red and White',
                nicknames: ['The Red Devils'],
                annualRevenue: '$700 million',
                ownership: 'The Glazer Family',
                notablePlayers: ['David Beckham', 'Eric Cantona', 'Ryan Giggs'],
                youthAcademy: 'Manchester United Academy',
                totalTrophies: 66,
                website: 'https://www.manutd.com',
                bio: 'Manchester United is one of the most widely supported football clubs in the world, known for its historic "Busby Babes" and "Class of \'92".',
                members: '200,000+'
            },
            {
                clubId: 3,
                img: "",
                teamName: 'Bayern Munich',
                leagueTitles: 33,
                cupTitles: 20,
                championsLeagueTitles: 6,
                europaLeagueTitles: 1,
                founded: 1900,
                league: 'Bundesliga',
                nation: 'Germany',
                city: 'Munich',
                stadium: 'Allianz Arena',
                stadiumCapacity: 75024,
                manager: 'Vincent Kompany',
                topScorer: 'Gerd Müller',
                topScorerGoals: 563,
                rivalClub: 'Borussia Dortmund',
                clubMotto: 'Mia San Mia',
                marketValue: '$4.2 billion',
                socialMediaFollowers: '100 million',
                colors: 'Red and White',
                nicknames: ['Die Bayern', 'FC Hollywood'],
                annualRevenue: '$750 million',
                ownership: '50+1 Rule (Member-owned)',
                notablePlayers: ['Franz Beckenbauer', 'Gerd Müller', 'Philipp Lahm'],
                youthAcademy: 'FC Bayern Munich Academy',
                totalTrophies: 80,
                website: 'https://www.fcbayern.com',
                bio: 'Bayern Munich is the most successful club in German football history and a powerhouse in European competitions.',
                members: '300,000+'
            },
            {
                clubId: 4,
                img: "IMG/Juventus_FC_-_pictogram_black_(Italy,_2017).svg.webp",
                teamName: 'Juventus FC',
                leagueTitles: 36,
                cupTitles: 14,
                championsLeagueTitles: 2,
                europaLeagueTitles: 3,
                founded: 1897,
                league: 'Serie A',
                nation: 'Italy',
                city: 'Turin',
                stadium: 'Allianz Stadium',
                stadiumCapacity: 41507,
                manager: 'Thiago Motta',
                topScorer: 'Alessandro Del Piero',
                topScorerGoals: 290,
                rivalClub: 'Inter Milan',
                clubMotto: 'Fino alla Fine',
                marketValue: '$2 billion',
                socialMediaFollowers: '100 million',
                colors: 'Black and White',
                nicknames: ['La Vecchia Signora', 'The Old Lady'],
                annualRevenue: '$500 million',
                ownership: 'Exor (Agnelli Family)',
                notablePlayers: ['Alessandro Del Piero', 'Gianluigi Buffon', 'Roberto Baggio'],
                youthAcademy: 'Juventus Next Gen',
                totalTrophies: 70,
                website: 'https://www.juventus.com',
                bio: 'Juventus is Italy’s most successful club, renowned for its solid defense and classic black-and-white kits.',
                members: '170,000+'
            },
            {
                clubId: 5,
                img: "IMG/Liverpool_FC.svg.webp",
                teamName: 'Liverpool FC',
                leagueTitles: 19,
                cupTitles: 8,
                championsLeagueTitles: 6,
                europaLeagueTitles: 3,
                founded: 1892,
                league: 'Premier League',
                nation: 'England',
                city: 'Liverpool',
                stadium: 'Anfield',
                stadiumCapacity: 54074,
                manager: 'Arne Slot',
                topScorer: 'Ian Rush',
                topScorerGoals: 346,
                rivalClub: 'Manchester United',
                clubMotto: 'You’ll Never Walk Alone',
                marketValue: '$4.1 billion',
                socialMediaFollowers: '100 million',
                colors: 'Red',
                nicknames: ['The Reds'],
                annualRevenue: '$600 million',
                ownership: 'Fenway Sports Group',
                notablePlayers: ['Steven Gerrard', 'Kenny Dalglish', 'Ian Rush'],
                youthAcademy: 'Liverpool FC Academy',
                totalTrophies: 68,
                website: 'https://www.liverpoolfc.com',
                bio: 'Liverpool is known for its passionate fan base and historic victories in both domestic and European competitions, including the iconic Anfield stadium.',
                members: '200,000+'
            },
            {
                clubId: 6,
                img: "IMG/Paris_Saint-Germain_F.C..svg.png",
                teamName: 'Paris Saint-Germain FC',
                leagueTitles: 11,
                cupTitles: 14,
                championsLeagueTitles: 0,
                europaLeagueTitles: 0,
                founded: 1970,
                league: 'Ligue 1',
                nation: 'France',
                city: 'Paris',
                stadium: 'Parc des Princes',
                stadiumCapacity: 47929,
                manager: 'Luis Enrique',
                topScorer: 'Edinson Cavani',
                topScorerGoals: 200,
                rivalClub: 'Olympique de Marseille',
                clubMotto: 'Ici c’est Paris',
                marketValue: '$3.2 billion',
                socialMediaFollowers: '150 million',
                colors: 'Blue and Red',
                nicknames: ['Les Parisiens'],
                annualRevenue: '$700 million',
                ownership: 'Qatar Sports Investments',
                notablePlayers: ['Zlatan Ibrahimović', 'Thiago Silva', 'Kylian Mbappé'],
                youthAcademy: 'PSG Academy',
                totalTrophies: 47,
                website: 'https://www.psg.fr',
                bio: 'Paris Saint-Germain, often abbreviated as PSG, is the most successful club in France and known for its recent acquisition of star players.',
                members: '150,000+'
            },
            {
                clubId: 7,
                img: "IMG/Logo_of_AC_Milan.svg.png",
                teamName: 'AC Milan',
                leagueTitles: 19,
                cupTitles: 5,
                championsLeagueTitles: 7,
                europaLeagueTitles: 0,
                founded: 1899,
                league: 'Serie A',
                nation: 'Italy',
                city: 'Milan',
                stadium: 'San Siro',
                stadiumCapacity: 80018,
                manager: 'Paulo Fonseca',
                topScorer: 'Gunnar Nordahl',
                topScorerGoals: 221,
                rivalClub: 'Inter Milan',
                clubMotto: 'Sempre Milan',
                marketValue: '$1.4 billion',
                socialMediaFollowers: '50 million',
                colors: 'Red and Black',
                nicknames: ['Rossoneri'],
                annualRevenue: '$250 million',
                ownership: 'RedBird Capital Partners',
                notablePlayers: ['Paolo Maldini', 'Franco Baresi', 'Andriy Shevchenko'],
                youthAcademy: 'AC Milan Academy',
                totalTrophies: 49,
                website: 'https://www.acmilan.com',
                bio: 'AC Milan is one of the most successful clubs in Italian and European football history, recognized for its red and black stripes and famous players.',
                members: '100,000+'
            },
            {
                clubId: 8,
                img: "IMG/Chelsea_FC.svg.webp",
                teamName: 'Chelsea FC',
                leagueTitles: 6,
                cupTitles: 8,
                championsLeagueTitles: 2,
                europaLeagueTitles: 2,
                founded: 1905,
                league: 'Premier League',
                nation: 'England',
                city: 'London',
                stadium: 'Stamford Bridge',
                stadiumCapacity: 40834,
                manager: 'Enzo Maresca',
                topScorer: 'Frank Lampard',
                topScorerGoals: 211,
                rivalClub: 'Arsenal',
                clubMotto: 'Blue is the Colour',
                marketValue: '$3.2 billion',
                socialMediaFollowers: '100 million',
                colors: 'Blue',
                nicknames: ['The Blues'],
                annualRevenue: '$600 million',
                ownership: 'Todd Boehly (Clearlake Capital)',
                notablePlayers: ['Didier Drogba', 'Frank Lampard', 'John Terry'],
                youthAcademy: 'Chelsea Academy',
                totalTrophies: 32,
                website: 'https://www.chelseafc.com',
                bio: 'Chelsea is known for its recent success in both domestic and European competitions, especially under the ownership of Roman Abramovich.',
                members: '120,000+'
            },
            {
                clubId: 9,
                img: "IMG/Manchester_City_FC_badge.svg.webp",
                teamName: 'Manchester City FC',
                leagueTitles: 9,
                cupTitles: 6,
                championsLeagueTitles: 1,
                europaLeagueTitles: 0,
                founded: 1880,
                league: 'Premier League',
                nation: 'England',
                city: 'Manchester',
                stadium: 'Etihad Stadium',
                stadiumCapacity: 53000,
                manager: 'Pep Guardiola',
                topScorer: 'Sergio Agüero',
                topScorerGoals: 260,
                rivalClub: 'Manchester United',
                clubMotto: 'Superbia in Proelio (Pride in Battle)',
                marketValue: '$4 billion',
                socialMediaFollowers: '80 million',
                colors: 'Sky Blue and White',
                nicknames: ['The Citizens', 'City'],
                annualRevenue: '$650 million',
                ownership: 'Sheikh Mansour (City Football Group)',
                notablePlayers: ['Sergio Agüero', 'David Silva', 'Kevin De Bruyne'],
                youthAcademy: 'Manchester City Academy',
                totalTrophies: 29,
                website: 'https://www.mancity.com',
                bio: 'Manchester City has emerged as one of the strongest clubs in recent years with a high-tempo style and significant investment in talent.',
                members: '130,000+'
            }
        
        ],
    },//Data

}//Model